spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/casedairy
spring.datasource.username=root
spring.datasource.password=Bhanudas@17
server.address=0.0.0.0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081