spring.application.name=backend

# ? H2 DATABASE (TEMP FIX)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=Bhanudas@17

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ? IMPORTANT FOR RENDER
server.port=${PORT:8080}
server.address=0.0.0.0

# ? ENABLE H2 CONSOLE (optional)
spring.h2.console.enabled=true